[package]
name = "adventofcode-rust-2022"
version = "0.0.0"
edition = "2021"

[profile.bench]
debug = true

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

anyhow = "1.0"
regex = "1.5"
ndarray = "0.15"
petgraph = "0.6"
bitlab = "1.1"
num-traits = "0.2"
num-derive = "0.3"
